name: accents
channels:
  - defaults
dependencies:
  - conda-forge::librosa=0.10.1
  - pytorch::torchvision==0.14.0
  - pytorch::torchaudio==0.13.0
  - pytorch::pytorch==1.13.0
  - python=3.10.4
  - conda-forge::ffmpeg
  - conda-forge::flask==3.0.0
  - pip:
    - numpy==1.26.3
